name: backend
services:
  database:
    container_name: database
    image: postgis/postgis:17-3.5-alpine
    restart: always
    ports:
      - "${PG_PORT}:5432"
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    networks:
      - backend-network
    volumes:
      - database-volume:/var/lib/postgresql/data
      - ./init-postgis.sql:/docker-entrypoint-initdb.d/init-postgis.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: backend-api
    restart: always
    image: api
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - "5000:5000"
    environment:
      PG_HOST: database
    networks:
      - backend-network
    depends_on:
      database:
        condition: service_healthy

networks:
  backend-network:
    driver: bridge

volumes:
  database-volume:
    name: "database-volume"